# Generated by Django 4.2.13 on 2024-06-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="word",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
