# Generated by Django 4.2.13 on 2024-06-05 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("words", "0002_alter_language_id_alter_word_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="created_by",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
